### ISSUE TITLE
install error from deb package /var/lib/polaric/mapcache/*.db

### ISSUE THREAD

**Issue by mv-T** [PolaricServer/webapp2#35]
hi,
i got an install error from polaric-webapp2 deb package on a fresh debian 10 maschine. the installer can`t find any mapcache db.
/var/lib/polaric/mapcache/*.db at installprocess. same process with config.js and mapcache.xml at /etc/polaric-webapp2/ these files will not created at installroutine. after i manual copy these files from git source at this locations the installprocess finished without error.

**Comment by ohanssen** [comment]
I believe this problem was addressed in release 1.6.1 and 1.6.2 (sorry I forgot to tag those here on Github).
