### ISSUE TITLE
Compilation - installation error

### ISSUE THREAD

**Issue by Skinoku** [PolaricServer/webapp2#36]
Dear ohanssen,
trying to install from source webapp2 I get this error (sorry if it is in Italian, I will happily clarify if needed):
`Preparativi per estrarre .../46-polaric-webapp2_1.6.2_all.deb...
dpkg: errore nell'elaborare l'archivio /tmp/apt-dpkg-install-O6HfLz/46-polaric-webapp2_1.6.2_all.deb (--unpack):
 il sottoprocesso nuovo pacchetto polaric-webapp2 script pre-installation ha restituito lo stato di errore 1
Selezionato il pacchetto proj-bin non precedentemente selezionato.
Preparativi per estrarre .../47-proj-bin_5.2.0-1_armhf.deb...
Estrazione di proj-bin (5.2.0-1)...
Si sono verificati degli errori nell'elaborazione:
 /tmp/apt-dpkg-install-O6HfLz/46-polaric-webapp2_1.6.2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Trying to compile webapp2 we get this error:
`ERROR - [JSC_READ_ERROR] Cannot read file application.js: application.js
`
What do you suggest?
Thanks

**Comment by ohanssen** [comment]
I am not sure. The pre-installation script seems to return status 1 which is an error. But I cannot see from this what is going wrong. 
To compile from source you need to fetch an example first. Use setup.sh.
