### ISSUE TITLE
Extend Basic Sample

### ISSUE THREAD

**Issue by alexander-pick** [PolaricServer/webapp2#38]
Is it possible to somehow extend basic to speak to the backend? At the moment it seems Basic is just a map and menus, very close to minimal. How to add APRS points from the backend to it?
I tried it with the polaric example but it seems broken for some reason and wants to connect websockets instead of port 8081. There are comments that the port should be used but no indicator how it is done.

**Comment by ohanssen** [comment]
To use the polaricserver-nordic example with your own backend, you need to comment out the following lines: 

SERVER("https://aprs.no");
WSPREFIX("ws");
AJAXPREFIX("srv");

Sorry, it was a mistake from my side. I'll check in a update... This example is very close to the setup of aprs.no, so maybe it is a good idea to have a simpler example with a backend. I'll look into it.

**Comment by alexander-pick** [comment]
Thanks a lot for the quick answer! Is it possible to document the proxy config you are using for the websockets? I want to open the instance to the public but I don't want the config panel public available.

**Comment by ohanssen** [comment]
To make it public you should of course have some knowlegde of how to set up a web server. It is a good idea to secure it and use TLS/SSL, which require certificates. You also need to decide if you want virtual hosts, other services, etc.. Do   I could perhaps write some doc for the Polaric Server setup in particular.

**Comment by alexander-pick** [comment]
I actually know that and wanted to place it behind cloudflare. But from your description it sounded like you proxy the websockets to a backend server based on these two endpoints in the config. At the moment I configured the entire system to work on my LAN and just use the backend hosted on 8081 by commenting the sockets out. In a live environment I want the websockets to work and have the backend server invisible/unreachable. But it seems I need to read a bit more into the source to understand what ways exist to access the backend data and craft that in a solution which works for me.

**Comment by ohanssen** [comment]
I have started adding som on this in the wiki doc. But I will need some time.. You will need mod_proxy, mod_proxy_http and mod_proxy_wstunnel. I use this for REST API: 

    ProxyPass /srv http://localhost:8081 nocanon
    ProxyPass /srv/* http://localhost:8081 nocanon
    ProxyPassReverse /srv http://localhost:8081
    SetEnv  proxy-nokeepalive 1
    ProxyTimeout 180

And this for Websocket. 

<Location "/ws/">
   ProxyPass ws://localhost:8081/
   ProxyPassReverse ws://localhost:8081/
   ProxyPreserveHost on
</Location>

I use virtual hosts and SSL and I have made two config files with this proxy setup (one for the https port). You may need some redirects and rewrites to make it work smoothly :)

**Comment by alexander-pick** [comment]
Thanks that helps me a lot!
