### ISSUE TITLE
Add support Plus Codes Grid layer

### ISSUE THREAD

**Issue by AntonShevchuk** [PolaricServer/webapp2#40]
I think it would be helpful for search operations https://grid.plus.codes

**Comment by ohanssen** [comment]
Polaric-webapp2 is based on OpenLayers, so it is easy to add it as a XYZ layer in config.js
In the example - just after "UTM/MGRS Grid", add another layer: 

    new ol.layer.Tile({
      name: "Plus codes grid",      
      source: new ol.source.XYZ({
        url: 'https://grid.plus.codes/grid/wms/{z}/{x}/{y}.png?col=red'
      }),
    })

I can add it to aprs.no
